[프로그래머스] 하샤드 수
solbi9382/Algorithm_Study pull request #26
Opened 2021-04-21 14:19 UTC by solbi9382

좀 더 효울적으로 짤 수 있을 것 같은데, 음주 코딩이라서,, 머리가 잘 안 돌아가네요 ㅠ^ㅠ

2021-04-21 14:23 UTC, MeteorSis requested changes

2021-04-21 14:23 UTC, MeteorSis commented on Javascript/harshadNumber.js
> +    const num = n
n을 num에 따로 저장할 필요가 없어보여요

2021-04-21 14:23 UTC, MeteorSis commented on Javascript/harshadNumber.js
> +    const splitNumber = num.toString().split('')
문자열 처리 없이 구현하는게 좋을 것 같아요

2021-04-22 12:25 UTC, solbi9382 commented on Javascript/harshadNumber.js
> +    const splitNumber = num.toString().split('')
숫자자체로 처리하는 방식으로 변경했습니다.
근데 이렇게 바꾸니까 테스트돌렸을 때 47점이 나오네요,, 뭐가 문제일까요,,,

문제링크 (https://programmers.co.kr/learn/courses/30/lessons/12947)

2021-04-22 12:36 UTC, MeteorSis commented on Javascript/harshadNumber.js
> +    const splitNumber = num.toString().split('')
디버깅해보시면 금방 원인 찾을 수 있을 것 같은데요?

2021-04-22 13:17 UTC, solbi9382 commented on Javascript/harshadNumber.js
> +    const splitNumber = num.toString().split('')
수정했습니다

2021-04-22 13:22 UTC, MeteorSis requested changes

2021-04-22 13:22 UTC, MeteorSis commented on Javascript/harshadNumber.js
> +    while (Math.floor(num) > 0) {
34행에서 Math.floor 함수 호출되서 num > 0으로도 충분할 것 같아요.

2021-04-22 13:22 UTC, MeteorSis commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
Math.floor가 javascript 부동소숫점 에러만 아니면 호출될 필요가 없긴 한데 어쩔 수 없긴 하네요
근데 부동소숫점 오류가 3.000000001과 같이 발생할 수도 있지만 2.999999999 같은 형태로 발생할 수도 있으니까 Math.floor보단 Math.round가 더 적절할 것 같아요.

2021-04-22 13:35 UTC, solbi9382 commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
round로 했을 때 통과 못하는 케이스가 있는 것 같아요~ 실제 돌려봤을 때 실패케이스가 있어서 100점이 안나옵니다.

2021-04-22 13:38 UTC, solbi9382 commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
round로 했을 때 실패하는 케이스가 존재해서, 테스트 통과가 안돼요~!
n이 12라고 하면 1 + 1.2 = 3.2222 인 경우엔 소수점 자리는 필요가 없기 때문에
floor써서 소수점 버리기를 했던거였어요~

2021-04-22 13:41 UTC, MeteorSis commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
```js
const solution = n => {
    let sum = 0
    let num = n // n값을 변경하지 않기 위해 변수에 저장
    while (num > 0) {
        sum += num % 10
        num = Math.floor(num / 10)
    }
    if (n % Math.round(sum) === 0) {
        return true
    } else {
        return false
    }
}
```
위 코드로 테스트 돌렸을 때 결과에요
```
테스트 1 〉 | 통과 (0.06ms, 30.3MB)
테스트 2 〉 | 통과 (0.06ms, 30.3MB)
테스트 3 〉 | 통과 (0.06ms, 29.9MB)
테스트 4 〉 | 통과 (0.06ms, 29.9MB)
테스트 5 〉 | 통과 (0.06ms, 30.2MB)
테스트 6 〉 | 통과 (0.06ms, 30MB)
테스트 7 〉 | 통과 (0.06ms, 30.2MB)
테스트 8 〉 | 통과 (0.06ms, 30MB)
테스트 9 〉 | 통과 (0.06ms, 30.1MB)
테스트 10 〉 | 통과 (0.20ms, 29.9MB)
테스트 11 〉 | 통과 (0.06ms, 30.3MB)
테스트 12 〉 | 통과 (0.06ms, 30MB)
테스트 13 〉 | 통과 (0.06ms, 30.1MB)
테스트 14 〉 | 통과 (0.06ms, 30.2MB)
테스트 15 〉 | 통과 (0.06ms, 30.3MB)
테스트 16 〉 | 통과 (0.06ms, 30MB)
테스트 17 〉 | 통과 (0.06ms, 30.1MB)
채점 결과
정확성: 100.0
합계: 100.0 / 100.0
```

2021-04-22 13:42 UTC, solbi9382 commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
34번째 줄에 코멘트 남겨서  num = Math.floor(num / 10) 여길 고쳤어요 ㅠㅠ

2021-04-22 13:45 UTC, solbi9382 commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
피드백 주신 내용 확인 후 코드 수정했습니다.

2021-04-22 13:45 UTC, MeteorSis commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
제가 보기엔 36번 행에 남긴 코멘트 같은데 버그가 있는 걸까요

2021-04-22 13:46 UTC, MeteorSis approved these changes
LGTM!

2021-04-22 13:47 UTC, solbi9382 commented on Javascript/harshadNumber.js
>      if (n % Math.floor(sum) === 0) {
![image](https://user-images.githubusercontent.com/26318691/115725316-b45b6600-a3bc-11eb-99d6-3e3ba1027a15.png)
전 이렇게 보였어요~

2021-04-22 13:48 UTC, merged