큰 수 출력하기
solbi9382/Algorithm_Study pull request #43
Opened 2021-05-19 13:15 UTC by solbi9382

2021-05-19 13:31 UTC, MeteorSis requested changes

2021-05-19 13:31 UTC, MeteorSis commented on Javascript/printMaxNumber.js
> +const solution = (arr) => {
설명이 좀 이해하기 어렵긴 한데 문제 이해를 잘못하고 문제를 푼 것 같아요.
> 첫 줄에 자연수 N이 주어지고, 그 다음 줄에 N개의 정수가 입력된다.

일단 위 문장에서 입력으로 들어온 첫 라인의 숫자 N 만큼 그 다음 줄의 숫자 N개를 파싱해야 할 것 같아요.
뭐 이건 실제 프로그래머스에서 인자가 어떻게 전달되는 지에 따라 스킵할 수 있는 것 같긴 해요.

문제는
> 자신의 바로 앞 수보다 큰 수만 출력하는 프로그램을 작성하세요.(첫 번째 수는 무조건 출력한다)

인데.
이건 7 3 9 5 6 12이 들어온다고 했을 때
코드 실행 순서는 다음과 같아요.
1. 첫 번째 수 7을 출력해요.
2. 3은 7보다 크지 않으므로 출력하지 않아요.
3. 9는 3보다 크므로 9를 출력해요.
4. 5는 9보다 크지 않으므로 출력하지 않아요.
5. 6은 5보다 크므로 6을 출력해요.
6. 12는 6보다 크므로 12를 출력해요.
이렇게 총 출력된 숫자는 7, 9, 6, 12가 되도록 구현해야 할 것 같아요.

2021-05-19 13:50 UTC, solbi9382 commented on Javascript/printMaxNumber.js
> +const solution = (arr) => {
문제가 C++,C로 되어있다보니 라인 이라는 게 있는데, 강의에서는 그냥 배열의 요소를 출력하는 것으로 해석하고 있습니다.

2021-05-19 13:50 UTC, solbi9382 commented on Javascript/printMaxNumber.js
> +const solution = (arr) => {
말한 방법대로 코드 수정은 해볼게요~

2021-05-20 13:16 UTC, solbi9382 commented on Javascript/printMaxNumber.js
> +const solution = (arr) => {
@MeteorSis 수정해써요 ^_^

2021-05-20 13:21 UTC, MeteorSis requested changes

2021-05-20 13:21 UTC, MeteorSis commented on Javascript/printMaxNumber.js
> +    let answer = []
const answer = [arr[0]]로 줄일 수 있을 것 같아요

2021-05-20 13:21 UTC, MeteorSis commented on Javascript/printMaxNumber.js
> +let arr = [7, 3, 9, 5, 6, 12]
const로 바꿔 주세요

2021-05-20 23:29 UTC, MeteorSis approved these changes
LGTM!

2021-05-21 02:28 UTC, merged