졸업 선물 문제 (선물할 수 있는 최대 가짓수)
solbi9382/Algorithm_Study pull request #59
Opened 2021-06-18 16:04 UTC by solbi9382

2021-06-18 16:05 UTC, solbi9382 commented on Javascript/getGiftNum.js
> +        let budget = money - (arr[i][0] / 2 + arr[i][1])  // 원래 상품 가격(arr[i][0])에 50% 할인된 가격 + 배송비로 계산
@MeteorSis 상품가격은 항상 짝수값이기때문에, 2로 나누면 소숫점단위없이 딱 떨어져서 Math.floor는 사용하지 않았습니다.

2021-06-21 08:23 UTC, MeteorSis requested changes

2021-06-21 08:23 UTC, MeteorSis commented on Javascript/getGiftNum.js
> +            }
```js
if (j !== i) {
    const itemPrice = arr[j][0] + arr[j][1]
    if (itemPrice > budget) {
        break
    } else {
        budget -= itemPrice
        cnt++
    }
}
```
로 바꾸는게 더 가독성이 좋을 것 같아요.

2021-06-21 10:51 UTC, MeteorSis approved these changes
LGTM!

2021-06-21 12:33 UTC, merged