[프로그래머스] 올바른 괄호
solbi9382/Algorithm_Study pull request #63
Opened 2021-07-01 14:23 UTC by solbi9382

이렇게 했었을 때 총 18개의 케이스에서 실패하는 케이스가 3개 존재합니다.

채점 결과
정확성: 57.9
효율성: 15.2
합계: 73.2 / 100.0

2021-07-02 03:35 UTC, MeteorSis commented
예전에 코테 문제에 xml 태그 파싱하는 문제 기억 나나요? 그 때 해결한 방법으로 풀어보면 쉽게 해결이 가능할 것 같아요

2021-07-09 02:20 UTC, MeteorSis commented
#64 풀이를 참조해서 풀어보세요

2021-07-12 14:00 UTC, solbi9382 commented
![image](https://user-images.githubusercontent.com/26318691/125300269-d386e580-e364-11eb-8294-d11c497fc7ef.png)

위 테스트 케이스에서는 다 통과했는데 막상 채점하면 결과는 69점이네요 ㅠㅠ

![image](https://user-images.githubusercontent.com/26318691/125300422-f913ef00-e364-11eb-8140-5dbd6a4870ac.png)

다른 케이스 생각해서 수정해보겠습니다.

2021-07-12 14:07 UTC, solbi9382 commented
"()))((()" 일 때는 false여야 하는데 true로 잘못 나오고 있었네요~
이 부분 처리해서 다시 코드 작성해보겠습니다!

2021-07-13 01:21 UTC, MeteorSis commented
> 다른 방식으로 풀이. 그래도 통과못함..ㅠ

위 커밋 접근 방식이 맞으나 거기서 #64 와는 다른 점이 #64 는 같음을 비교한다면 이 문제는 괄호의 닫힘 여부를 판단한다는 점이에요.

오히려
> 괄호 개수 저장 비교하는 방식으로 변경&& 모든 케이스 커버하도록 코드 수정중

위 커밋은 갯수만 파악하지 닫힘을 확인한다는 측면에서는 적절치 못한 풀이라고 생각해요.

2021-07-23 01:47 UTC, MeteorSis requested changes

2021-07-23 01:47 UTC, MeteorSis commented on Javascript/getCorrectParentheses.js
> +    let answer = true;
answer라는 값을 로직에서 활용할 게 아니라면 변수 선언을 없애고 44번을 return true로 바꾸는게 더 좋아보여요.

2021-07-26 02:23 UTC, MeteorSis approved these changes
LGTM!

2021-07-26 02:24 UTC, merged