대문자로 통일
solbi9382/Algorithm_Study pull request #74
Opened 2023-02-10 04:57 UTC by solbi9382

어제 푼 문제랑 비슷한 유형이여서, 비슷한 방식으로 풀었습니다.

2023-02-10 05:41 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +      s = s.toUpperCase();
이부분 내장 함수 말고 대문자와 소문자 간의 차이를 이용해서 직접 계산하는 방식으로도 풀어보면 좋을 것 같아요

2023-02-13 07:28 UTC, solbi9382 commented on Javascript/integrateUppercase.js
> +      s = s.toUpperCase();
@MeteorSis https://github.com/solbi9382/Algorithm_Study/pull/74/commits/6cad8ffdea1449f3adb4d2cf38b3f4d0e8410f6d
이 커밋 내용 확인 부탁드려요~

2023-02-13 08:41 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +    if (s >= "a" && s <= "z") result += String.fromCharCode(asciiCode - 32);
소문자와 대문자의 차이가 32라는 아스키코드 차이가 있다는 사실을 알고 쓰는 것이 아니라 그 차이를 코드에서 계산해서 변환했으면 좋겠다는 뜻이었어요.

2023-02-13 08:41 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +      s = s.toUpperCase();
소문자와 대문자의 차이가 32라는 아스키코드 차이가 있다는 사실을 알고 쓰는 것이 아니라 그 차이를 코드에서 계산해서 변환했으면 좋겠다는 뜻이었어요.

2023-02-16 15:05 UTC, MeteorSis requested changes

2023-02-16 15:05 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +    let asciiCode = s.charCodeAt();
아스키 코드 산출 자체도 글자가 소문자일 때만 필요한데 if문 밖에 있어서 모든 loop마다 `charCodeAt`이 실행되는 건 낭비로 보여요.

2023-02-16 15:05 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +      );
이건 산술 연산으로 봤을 때 `result += String.fromCharCode(s.toUpperCase().charCodeAt())`랑 동일한거고, 이건 사실 아스키코드를 이용했다기 보단 `s.toUpperCase()`만 사용한 거랑 동일한 것 같아요.
그리고 특정 글자의 대문자와 소문자의 차이는 항상 동일한 것인데(기존 코드에 박았던 32이라는 차이) 이 차이가 굳이 for문의 loop 한번 한번마다 계속 산술되어야할 필요도 없어보여요.

수정의 순서는 이렇게 될 것 같아요.
1. for문 밖에서 대문자와 소문자의 아스키 코드 차이 값을 산출한다.
2. for문 안에서 글자가 소문자일 때 분기 안에서 기존 소문자 아스키 코드 값과 앞에서 산출한 아스키 코드 값을 더하거나 빼고 그 아스키 코드 값으로 `String.fromCharCode`를 호출해 글자를 생성한다.
3. 그 글자를 result에 더한다.

2023-02-17 12:02 UTC, MeteorSis commented on Javascript/integrateUppercase.js
> +      let asciiCode = s.charCodeAt();
```suggestion
      const asciiCode = s.charCodeAt();
```
asciiCode 변수 변동이 발생하지 않으니 const가 더 좋을 것 같네요.

2023-02-17 13:46 UTC, solbi9382 commented on Javascript/integrateUppercase.js
> +      let asciiCode = s.charCodeAt();
넵 변경했습니다!

2023-02-17 14:04 UTC, MeteorSis approved these changes
LGTM!

2023-02-17 14:05 UTC, merged